on:
  pull_request:
    paths:
      - "**.go"
      - "**.yml"
  push:
    branches:
      - master
name: Build PR
jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Fetch Git Tags
        run: |
          git fetch --prune --unshallow --tags
      - name: Get SHORT SHA
        id: shortsha
        run: | 
          echo "::set-output name=sha8::$(echo ${{github.event.pull_request.head.sha}} | cut -c1-8)"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
          stable: true
        id: go
      - name: Cross Platform Build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make cross
      - name: Test
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make test 
      - uses: LanceMcCarthy/Action-AzureBlobUpload@v1.8.0
        name: Uploading to Azure storage...
        with:
          connection_string: ${{ secrets.az_connection_string }}
          container_name: gopogh
          source_folder: ./out
          destination_folder: ${{github.event.number}}/${{ steps.shortsha.outputs.sha8 }}
          clean_destination_folder: true
          fail_if_source_empty: true
      - name: Report url
        shell: bash
        run: |
          echo "*******************************************************"
          echo "https://gopogh.blob.core.windows.net/gopogh/${{github.event.number}}/${{ steps.shortsha.outputs.sha8 }}/output.html"
          echo "https://gopogh.blob.core.windows.net/gopogh/${{github.event.number}}/${{ steps.shortsha.outputs.sha8 }}/output.html"
          echo "*******************************************************"
          