on:
  pull_request:
    paths:
      - "**.go"
      - "**.yml"
  push:
    branches:
      - master
name: Build PR
jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Fetch Git Tags
        run: |
          git fetch --prune --unshallow --tags
      - name: Get SHORT SHA
        id: shortsha
        run: | 
          echo "::set-output name=sha8::$(echo ${{github.event.pull_request.head.sha}} | cut -c1-8)"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
          stable: true
        id: go
      - name: install rice
        run: | 
          go get github.com/GeertJohan/go.rice
          go get github.com/GeertJohan/go.rice/rice
      - name: Cross Platform Build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make cross
      - name: Test
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make test
      - name: Report url
        shell: bash
        run: |
          echo "*******************************************************"
          echo "https://gopogh.blob.core.windows.net/gopogh/${{github.event.number}}/${{ steps.shortsha.outputs.sha8 }}/output.html"
          echo "https://gopogh.blob.core.windows.net/gopogh/${{github.event.number}}/${{ steps.shortsha.outputs.sha8 }}/output.html"
          echo "*******************************************************"
